/**
 * Converts the text scraped from a GeeksForGeeks problem into readable Markdown.
 * GFG frequently places example labels in inline elements, so uploading its HTML
 * directly causes GitHub to display the statement as one long paragraph.
 */
export function formatGfgProblemReadme(title, difficulty, statement = '', questionUrl = '') {
  const text = String(statement)
    .replace(/\u00a0/g, ' ')
    .replace(/\r\n?/g, '\n')
    .replace(/[ \t]+\n/g, '\n')
    .trim();

  const escapeHtml = value => value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');

  // Depending on GFG's markup, the heading is extracted either as
  // "Examples: Input:" or "Examples Input:".
  const examplesMatch = text.match(/\bExamples?\s*:?\s*(?=Input\s*:)/i);
  const intro = examplesMatch ? text.slice(0, examplesMatch.index).trim() : text;
  const examples = examplesMatch ? text.slice(examplesMatch.index + examplesMatch[0].length).trim() : '';
  let formattedStatement = `<p>${escapeHtml(intro)}</p>`;

  if (examples) {
    // Each GFG example starts with Input. Group its labels in a <pre> block,
    // matching the code-style example blocks generated by LeetCode.
    const inputParts = examples.split(/\s*(?=Input\s*:)/i).filter(Boolean);
    const renderedExamples = inputParts.map((part, index) => {
      const nextSection = part.search(/\s*(?=Constraints\s*:|Expected\s+(?:Time|Auxiliary\s+Space)\s+Complexity\s*:)/i);
      const example = (nextSection >= 0 ? part.slice(0, nextSection) : part).trim();
      const remainder = nextSection >= 0 ? part.slice(nextSection).trim() : '';
      const block = `<p><strong>Example ${index + 1}:</strong></p><pre>${escapeHtml(
        example.replace(/\s*(Input|Output|Explanation)\s*:\s*/gi, (_match, label) =>
          `${label}: `
        ).replace(/\s*(?=Output:|Explanation:)/g, '\n').trim()
      )}</pre>`;
      return remainder
        ? `${block}<p><strong>${escapeHtml(remainder)}</strong></p>`
        : block;
    });
    formattedStatement += `<p><strong>Examples:</strong></p>${renderedExamples.join('')}`;
  }

  // Match the per-problem README template used by LeetCode.
  const heading = questionUrl
    ? `<h2><a href="${questionUrl}">${title}</a></h2>`
    : `<h2>${title}</h2>`;

  return `${heading}<h3>${difficulty || 'Unknown'}</h3><hr>${formattedStatement}`;
}
